### ISSUE TITLE
Sorting issues in submission inbox

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-mod_turnitintooltwo#365]
## Summary
Assignments where only some students have submitted have been known to sort incorrectly (i.e. non-alphabetically) on student first name.

**Comment by MarkRoche1** [comment]
Hi David,

We've just upgraded to Turnitin v2017112301 and have encountered this bug. Is it fixed in the latest version? If not, are there any workarounds?

Thanks
Mark

**Comment by cb526** [comment]
Just reporting that this bug is still present.

**Comment by sleitao** [comment]
Just to confirm that the issue is still present in version 2020072201.
It doesn't sort by student first name.

**Comment by upascal** [comment]
I also have this bug. How do we fix it?

**Comment by jack-tii** [comment]
This was fixed in our latest release
